# Generated by Django 3.1.3 on 2020-11-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benih',
            old_name='jumlah',
            new_name='jumlah_beras',
        ),
        migrations.RemoveField(
            model_name='benih',
            name='nama',
        ),
        migrations.AddField(
            model_name='benih',
            name='jumlah_jagung',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benih',
            name='jumlah_kacang',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
